#!/bin/sh

THIS_SCRIPT=$(realpath "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

SRC_DIR="$THIS_SCRIPT_DIR"
JARS_DIR="$THIS_SCRIPT_DIR"
CACHE_DIR="$THIS_SCRIPT_DIR/cache"
OUR_JAR_FILE="$CACHE_DIR/akgcode.jar"

CLASSPATH="$JARS_DIR/scallop_2.12-3.0.3.jar:$JARS_DIR/commons-io-2.5.jar:$JARS_DIR/jgrapht-core-1.0.1.jar"

mkdir -p "$CACHE_DIR"

# Recompile cached jar file
if test "(" "!" "(" "-e" "$OUR_JAR_FILE"  ")" ")"  -o "(" "$SRC_DIR/akgcode.scala" -nt "$OUR_JAR_FILE" ")"; then
    scalac -classpath "$CLASSPATH"\
           -deprecation \
           -Xfatal-warnings \
           -Xlint \
           -d "$OUR_JAR_FILE" \
           "$SRC_DIR/akgcode.scala" \
           || exit
fi

scala -classpath "$CLASSPATH"\
       -J-Xmx8G \
       -J-server \
       -J-XX:+AggressiveOpts \
       -J-XX:+UseParNewGC \
       -J-XX:+UseConcMarkSweepGC \
       -deprecation \
       "$OUR_JAR_FILE" \
       "$@"
